dist: trusty
sudo: false

language: go

go:
  - 1.8

before_install:
  - export TZ=America/New_York

addons:
  postgresql: "9.5"

before_script:
  - psql -c 'create database "likeness-test";' -U postgres
